In [1]:
import pandas as pd
import datetime as datetime
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r'C:\Users\User\Desktop\python\covid_19_till_19_May_2020.csv')

In [3]:
df.head()

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered
0,NaN,Afghanistan,33.0000,65.0000,1/22/20,0,0,0
1,NaN,Albania,41.1533,20.1683,1/22/20,0,0,0
2,NaN,Algeria,28.0339,1.6596,1/22/20,0,0,0
3,NaN,Andorra,42.5063,1.5218,1/22/20,0,0,0
4,NaN,Angola,-11.2027,17.8739,1/22/20,0,0,0

In [4]:
df.drop(['Lat','Long'],axis=1,inplace=True)

In [5]:
df.head()

  Province/State Country/Region     Date  Confirmed  Deaths  Recovered
0            NaN    Afghanistan  1/22/20          0       0          0
1            NaN        Albania  1/22/20          0       0          0
2            NaN        Algeria  1/22/20          0       0          0
3            NaN        Andorra  1/22/20          0       0          0
4            NaN         Angola  1/22/20          0       0          0

In [6]:
df.rename(columns={'Province/State':'Province','Country/Region':'Country'}, inplace=True)

In [7]:
df.columns

Index(['Province', 'Country', 'Date', 'Confirmed', 'Deaths', 'Recovered'], dtype='object')

In [8]:
df.head()

  Province      Country     Date  Confirmed  Deaths  Recovered
0      NaN  Afghanistan  1/22/20          0       0          0
1      NaN      Albania  1/22/20          0       0          0
2      NaN      Algeria  1/22/20          0       0          0
3      NaN      Andorra  1/22/20          0       0          0
4      NaN       Angola  1/22/20          0       0          0

In [9]:
df.Date = pd.to_datetime(df['Date'])

In [10]:
df.head()

  Province      Country       Date  Confirmed  Deaths  Recovered
0      NaN  Afghanistan 2020-01-22          0       0          0
1      NaN      Albania 2020-01-22          0       0          0
2      NaN      Algeria 2020-01-22          0       0          0
3      NaN      Andorra 2020-01-22          0       0          0
4      NaN       Angola 2020-01-22          0       0          0

In [11]:
df.isnull().sum()

Province     22015
Country          0
Date             0
Confirmed        0
Deaths           0
Recovered        0
dtype: int64

In [12]:
df.shape[0]

31535

In [13]:
idx = df['Province'].isnull()
df['Province'][idx] = 'other'

C:\Users\User\AppData\Local\Temp/ipykernel_15964/2987856898.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Province'][idx] = 'other'

In [14]:
df.head(10)

,Province,Country,Date,Confirmed,Deaths,Recovered
0,other,Afghanistan,2020-01-22,0,0,0
1,other,Albania,2020-01-22,0,0,0
2,other,Algeria,2020-01-22,0,0,0
3,other,Andorra,2020-01-22,0,0,0
4,other,Angola,2020-01-22,0,0,0
5,other,Antigua and Barbuda,2020-01-22,0,0,0
6,other,Argentina,2020-01-22,0,0,0
7,other,Armenia,2020-01-22,0,0,0
8,Australian Capital Territory,Australia,2020-01-22,0,0,0
9,New South Wales,Australia,2020-01-22,0,0,0

In [15]:
df.groupby(['Country']).sum()

                    Confirmed  Deaths  Recovered
Country
Afghanistan            115615    3211      13641
Albania                 34319    1408      20212
Algeria                183263   19089      76184
Andorra                 36237    1862      16176
Angola                   1452     106        383
...                       ...     ...        ...
West Bank and Gaza      17029      95       6333
Western Sahara            256       0        144
Yemen                    1190     190         30
Zambia                   8987     166       3102
Zimbabwe                 1386     171        226

[188 rows x 3 columns]

In [16]:
C = df.Country.unique()

In [17]:
C

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Benin', 'Bhutan', 'Bolivia',
       'Bosnia and Herzegovina', 'Brazil', 'Brunei', 'Bulgaria',
       'Burkina Faso', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Congo (Brazzaville)', 'Congo (Kinshasa)', 'Costa Rica',
       "Cote d'Ivoire", 'Croatia', 'Diamond Princess', 'Cuba', 'Cyprus',
       'Czechia', 'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador',
       'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon',
       'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Guatemala',
       'Guinea', 'Guyana', 'Haiti', 'Holy See', 'Honduras', 'Hungary',
       'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland',
       'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan',
       'Kenya', 'South Korea', 'Kuwait', 'Kyrgyzstan', 'Latvia',
       'Lebanon', 'Liberia', 'Liechtenstein', 'Lithuania', 'Luxembourg',
       'Madagascar', 'Malaysia', 'Maldives', 'Malta', 'Mauritania',
       'Mauritius', 'Mexico', 'Moldova', 'Monaco', 'Mongolia',
       'Montenegro', 'Morocco', 'Namibia', 'Nepal', 'Netherlands',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Macedonia',
       'Norway', 'Oman', 'Pakistan', 'Panama', 'Papua New Guinea',
       'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar',
       'Romania', 'Russia', 'Rwanda', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'San Marino', 'Saudi Arabia',
       'Senegal', 'Serbia', 'Seychelles', 'Singapore', 'Slovakia',
       'Slovenia', 'Somalia', 'South Africa', 'Spain', 'Sri Lanka',
       'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Taiwan*',
       'Tanzania', 'Thailand', 'Togo', 'Trinidad and Tobago', 'Tunisia',
       'Turkey', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'Uruguay', 'US', 'Uzbekistan', 'Venezuela',
       'Vietnam', 'Zambia', 'Zimbabwe', 'Dominica', 'Grenada',
       'Mozambique', 'Syria', 'Timor-Leste', 'Belize', 'Laos', 'Libya',
       'West Bank and Gaza', 'Guinea-Bissau', 'Mali',
       'Saint Kitts and Nevis', 'Kosovo', 'Burma', 'MS Zaandam',
       'Botswana', 'Burundi', 'Sierra Leone', 'Malawi', 'South Sudan',
       'Western Sahara', 'Sao Tome and Principe', 'Yemen', 'Comoros',
       'Tajikistan', 'Lesotho'], dtype=object)

In [18]:
len(C)

188

In [19]:
df.groupby(['Country','Date']).sum()

                        Confirmed  Deaths  Recovered
Country     Date
Afghanistan 2020-01-22          0       0          0
            2020-01-23          0       0          0
            2020-01-24          0       0          0
            2020-01-25          0       0          0
            2020-01-26          0       0          0
...                           ...     ...        ...
Zimbabwe    2020-05-15         42       4         13
            2020-05-16         42       4         13
            2020-05-17         44       4         17
            2020-05-18         46       4         18
            2020-05-19         46       4         18

[22372 rows x 3 columns]

In [20]:
df.groupby(['Date']).sum()

            Confirmed  Deaths  Recovered
Date
2020-01-22        555      17         28
2020-01-23        654      18         30
2020-01-24        941      26         36
2020-01-25       1434      42         39
2020-01-26       2118      56         52
...               ...     ...        ...
2020-05-15    4542341  307666    1600051
2020-05-16    4634062  311781    1655256
2020-05-17    4713614  315185    1695290
2020-05-18    4801937  318481    1747514
2020-05-19    4897486  323285    1648440

[119 rows x 3 columns]

In [21]:
df.head()

  Province      Country       Date  Confirmed  Deaths  Recovered
0    other  Afghanistan 2020-01-22          0       0          0
1    other      Albania 2020-01-22          0       0          0
2    other      Algeria 2020-01-22          0       0          0
3    other      Andorra 2020-01-22          0       0          0
4    other       Angola 2020-01-22          0       0          0

In [22]:
idx = df[(df['Date']>'2020-03-20') & (df['Date']<='2020-04-20')]

In [23]:
idx

      Province                Country       Date  Confirmed  Deaths  Recovered
15635    other            Afghanistan 2020-03-21         24       0          1
15636    other                Albania 2020-03-21         76       2          2
15637    other                Algeria 2020-03-21        139      15         32
15638    other                Andorra 2020-03-21         88       0          1
15639    other                 Angola 2020-03-21          2       0          0
...        ...                    ...        ...        ...     ...        ...
23845    other  Sao Tome and Principe 2020-04-20          4       0          0
23846    other                  Yemen 2020-04-20          1       0          0
23847    other                Comoros 2020-04-20          0       0          0
23848    other             Tajikistan 2020-04-20          0       0          0
23849    other                Lesotho 2020-04-20          0       0          0

[8215 rows x 6 columns]

In [24]:
df['Date'] >'2020-03-20'

0        False
1        False
2        False
3        False
4        False
         ...
31530     True
31531     True
31532     True
31533     True
31534     True
Name: Date, Length: 31535, dtype: bool

In [25]:
df['Date']<'2020-4-20'

0         True
1         True
2         True
3         True
4         True
         ...
31530    False
31531    False
31532    False
31533    False
31534    False
Name: Date, Length: 31535, dtype: bool

In [26]:
C[10]

'Azerbaijan'

In [27]:
C[167]

'Belize'

In [28]:
C[90]

'Lithuania'

In [29]:
C[100]

'Monaco'

In [30]:
df[df['Country']==C[100]]

      Province Country       Date  Confirmed  Deaths  Recovered
160      other  Monaco 2020-01-22          0       0          0
425      other  Monaco 2020-01-23          0       0          0
690      other  Monaco 2020-01-24          0       0          0
955      other  Monaco 2020-01-25          0       0          0
1220     other  Monaco 2020-01-26          0       0          0
...        ...     ...        ...        ...     ...        ...
30370    other  Monaco 2020-05-15         96       4         87
30635    other  Monaco 2020-05-16         96       4         87
30900    other  Monaco 2020-05-17         96       4         87
31165    other  Monaco 2020-05-18         97       4         87
31430    other  Monaco 2020-05-19         97       4         87

[119 rows x 6 columns]

In [31]:
df[df['Country']==df.Country.unique()[120]]

      Province Country       Date  Confirmed  Deaths  Recovered
183      other  Poland 2020-01-22          0       0          0
448      other  Poland 2020-01-23          0       0          0
713      other  Poland 2020-01-24          0       0          0
978      other  Poland 2020-01-25          0       0          0
1243     other  Poland 2020-01-26          0       0          0
...        ...     ...        ...        ...     ...        ...
30393    other  Poland 2020-05-15      18016     907       6918
30658    other  Poland 2020-05-16      18257     915       7175
30923    other  Poland 2020-05-17      18529     925       7451
31188    other  Poland 2020-05-18      18885     936       7628
31453    other  Poland 2020-05-19      19268     948       7903

[119 rows x 6 columns]

In [32]:
df[df['Country']==df.Country.unique()[100]]

      Province Country       Date  Confirmed  Deaths  Recovered
160      other  Monaco 2020-01-22          0       0          0
425      other  Monaco 2020-01-23          0       0          0
690      other  Monaco 2020-01-24          0       0          0
955      other  Monaco 2020-01-25          0       0          0
1220     other  Monaco 2020-01-26          0       0          0
...        ...     ...        ...        ...     ...        ...
30370    other  Monaco 2020-05-15         96       4         87
30635    other  Monaco 2020-05-16         96       4         87
30900    other  Monaco 2020-05-17         96       4         87
31165    other  Monaco 2020-05-18         97       4         87
31430    other  Monaco 2020-05-19         97       4         87

[119 rows x 6 columns]

In [33]:
from datetime import datetime

In [34]:
df[(df['Date'] >'2020-03-20') & (df['Date'] <= datetime(2020,4,20))]

      Province                Country       Date  Confirmed  Deaths  Recovered
15635    other            Afghanistan 2020-03-21         24       0          1
15636    other                Albania 2020-03-21         76       2          2
15637    other                Algeria 2020-03-21        139      15         32
15638    other                Andorra 2020-03-21         88       0          1
15639    other                 Angola 2020-03-21          2       0          0
...        ...                    ...        ...        ...     ...        ...
23845    other  Sao Tome and Principe 2020-04-20          4       0          0
23846    other                  Yemen 2020-04-20          1       0          0
23847    other                Comoros 2020-04-20          0       0          0
23848    other             Tajikistan 2020-04-20          0       0          0
23849    other                Lesotho 2020-04-20          0       0          0

[8215 rows x 6 columns]

In [35]:
import datetime as datetime

In [36]:
df[(df['Date'] >'2020-03-20') & (df['Date'] <= datetime.datetime(2020,4,20))]

      Province                Country       Date  Confirmed  Deaths  Recovered
15635    other            Afghanistan 2020-03-21         24       0          1
15636    other                Albania 2020-03-21         76       2          2
15637    other                Algeria 2020-03-21        139      15         32
15638    other                Andorra 2020-03-21         88       0          1
15639    other                 Angola 2020-03-21          2       0          0
...        ...                    ...        ...        ...     ...        ...
23845    other  Sao Tome and Principe 2020-04-20          4       0          0
23846    other                  Yemen 2020-04-20          1       0          0
23847    other                Comoros 2020-04-20          0       0          0
23848    other             Tajikistan 2020-04-20          0       0          0
23849    other                Lesotho 2020-04-20          0       0          0

[8215 rows x 6 columns]

In [37]:
from bokeh.plotting import figure,output_file,show

In [38]:
output_file('demo.html')
p = figure(plot_width = 800,plot_height=400,title='demo')
p.line([1,2,3,4,5],[6,7,8,9,10],line_width=2)
show(p)

In [39]:
from bokeh.io import output_notebook
output_notebook()

In [40]:
p = figure(plot_width = 400,plot_height=300,title='demo')
p.line([1,2,3,4,5],[6,7,8,9,10],line_width=2)
show(p)

In [41]:
p = figure(plot_width=400,plot_height=300,title='Bokeh Example',
          x_axis_label='X',y_axis_label='Y')
x = np.linspace(-2,2,30)
y1 = np.sin(x)
y2 = np.cos(x)
y3 = y1+y2-0.5
p.line(x,y1,legend='sin(x)',color = 'blue')
p.circle(x,y2,legend='cos(x)',fill_color='green',size=5)
p.triangle(x,y3,legend='sin(x)+cos(x)',color = 'red')
show(p)

BokehDeprecationWarning: 'legend' keyword is deprecated, use explicit 'legend_label', 'legend_field', or 'legend_group' keywords instead
BokehDeprecationWarning: 'legend' keyword is deprecated, use explicit 'legend_label', 'legend_field', or 'legend_group' keywords instead
BokehDeprecationWarning: 'legend' keyword is deprecated, use explicit 'legend_label', 'legend_field', or 'legend_group' keywords instead

In [42]:
from bokeh.layouts import gridplot

In [43]:
x = np.linspace(-2,2,30)
y1 = np.sin(x)
y2 = np.cos(x)
y3 = y1+y2-0.5
s1 = figure(plot_width=300,plot_height=200)
s1.circle(x,y1,size=10,color='navy',alpha = 0.7)

s2 = figure(plot_width=300,plot_height=200)
s2.triangle(x,y2,size=10,color='firebrick',alpha = 0.7)

s3 = figure(plot_width=300,plot_height=200)
s3.square(x,y3,size=10,color='olive',alpha = 0.7)
p = gridplot([[s1,s2,s3]])
show(p)

In [44]:
#conda install plotly
#conda install bokeh

In [45]:
import plotly.graph_objs as go

ModuleNotFoundError: No module named 'plotly'

In [ ]:
Z = np.linspace(0,10,50)
X = np.cos(Z)
Y = np.sin(Z)
trace = go.Scatter3d(x=X,y=Y,z=Z,
                    mode = 'markers',
                    marker=dict(size=12,color=Z,colorscale='Viridis'))
layout=go.Layout(title="3D interactive plot")
fig = go.Figure(data=[trace],layout=layout)
fig.show()

In [ ]:
X,Y = np.meshgrid(np.linspace(-2,2,30),np.linspace(-2,2,30))
Z = np.cos(X**2 + Y**2)
trace = go.Surface(x=X,y=Y,z=Z)
go.Figure(data = [trace],layout=go.Layout(title='3D Surface')).show()

In [ ]:
#conda install folium
#pip install folium

In [ ]:
import folium
m = folium.Map()
m

In [ ]:
df = pd.read_csv(r'C:\Users\DeLL\Desktop\ML\fullcourse\DV\data\covid_19_till_19_May_2020.csv')

In [ ]:
df.head()

In [ ]:
m = folium.Map()
df['Date'] = pd.to_datetime(df['Date'])
df2 = df[df['Date']==max(df['Date'])]

In [ ]:
df2

In [ ]:
for i in range(0,len(df2)):
    folium.Circle(location=[df2.iloc[i]['Lat'],df2.iloc[i]['Long']],
                  color='crimson',fill='crimson',
                  radius=int(df2.iloc[i]['Confirmed'])).add_to(m)
m

In [ ]:
df = pd.DataFrame({'A':np.random.normal(0,1,1000),
                   'B':np.random.normal(-2,2,1000),
                  'C': np.random.normal(5,4,1000)})

In [ ]:
df.head()

In [ ]:
df.plot()

In [ ]:
df.plot.hist(alpha=0.5)

In [ ]:
df.plot.hist(stacked=False,bins=30)

In [ ]:
df2 = pd.DataFrame(np.random.rand(10,4),columns=list('abcd'))

In [ ]:
df2.plot.area(stacked=False)

In [ ]:
df3 = pd.DataFrame(3*np.random.rand(4,2),
                  index=list('abcd'),
                  columns=list('xy'))

In [ ]:
df3

In [ ]:
df3.plot.pie(subplots=True,figsize=(6,8))